<a href="https://colab.research.google.com/github/jhiasab27/Linear-Algebra---58019/blob/main/LA_Final_Exam_(12_17_21).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Final Exam

In [33]:
import numpy as np
from scipy.linalg import solve 
A= np.array([[1,1,1],[1,-1,0],[3,0,0]])
B= np.array([[89],[6],[1]])
print(A)
print(B)

X= np.linalg.solve(A,B)
print("\n",X)

[[ 1  1  1]
 [ 1 -1  0]
 [ 3  0  0]]
[[89]
 [ 6]
 [ 1]]

 [[ 0.33333333]
 [-5.66666667]
 [94.33333333]]


###Problem 2. Solve each system: (30 points)

3x - y + z = 5

9x - 3y +3z = 15

-12x +4y -4z = -20 

In [28]:
#Cannot be solved as the resulting matrix (from the linear equations) is a singular matrix. This means it has no inverse and its determinant is 0.
#If you let A=LL^T and attempt to solve for "c", the result will be an imaginary number.

import numpy as np
from scipy.linalg import solve 
A= np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
B= np.array([[5],[15],[-20]])
print(A)
print(B)

X= np.linalg.solve(A,B) 
print("\n",X)

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
[[  5]
 [ 15]
 [-20]]


LinAlgError: ignored

###Problem 3. Consider the matrix, (40 points)
1.Find the eigenvalue/s

2.Find the eigenvectors

In [32]:
import numpy as np
A=np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
w,v=np.linalg.eig(A)
print("The eigenvalues are:")
print(w.round(),"\n")
print("The right eigenvectors are:")
print(v.round())

The eigenvalues are:
[-1.  3.  2.] 

The right eigenvectors are:
[[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
