<a href="https://colab.research.google.com/github/jhiasab27/Linear-Algebra---58019/blob/main/LA_Linear_Transformation_(11_3_21).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Using Python Codes to find the inverse of a given matrix

To find the inverse of a matrix, the matrix is passed to the linal.inv() of the NumPy module:

In [5]:
import numpy as np
A=np.array([[4,3],[-5,9]]) #creation of matrix A
print(A)
inv_A=np.linalg.inv(A)
print(inv_A)

[[ 4  3]
 [-5  9]]
[[ 0.17647059 -0.05882353]
 [ 0.09803922  0.07843137]]


In [6]:
B=np.array([[20],[26]])
print(B)

[[20]
 [26]]


In [7]:
X=np.linalg.inv(A).dot(B)
print(X)

[[2.]
 [4.]]


In [9]:
X=np.dot(inv_A,B)
print(X)

[[2.]
 [4.]]


In [12]:
C=np.array([[4,3,2],[-2,2,3],[3,-5,2]])
print(C)
inv_C=np.linalg.inv(C)
print(inv_C)

[[ 4  3  2]
 [-2  2  3]
 [ 3 -5  2]]
[[ 0.15447154 -0.1300813   0.04065041]
 [ 0.10569106  0.01626016 -0.1300813 ]
 [ 0.03252033  0.23577236  0.11382114]]


In [21]:
D=np.array([[25],[-10],[-4]])
print(D)

[[ 25]
 [-10]
 [ -4]]


In [13]:
Y=np.linalg.inv(C).dot(D)
print(Y)

[[ 5.]
 [ 3.]
 [-2.]]


In [14]:
Y=np.dot(inv_C,D)
print(Y)

[[ 5.]
 [ 3.]
 [-2.]]


##Application

In [16]:
A=np.array([[20,10],[17,22]])
print(A)

inv_A=np.linalg.inv(A)
print(inv_A)

[[20 10]
 [17 22]]
[[ 0.08148148 -0.03703704]
 [-0.06296296  0.07407407]]


In [17]:
B=np.array([[350],[500]])
print(B)

[[350]
 [500]]


In [18]:
X=np.dot(inv_A,B)
print(X)

[[10.]
 [15.]]


##Checking

In [20]:
B=np.dot(A,X)
print(B)

[[350.]
 [500.]]
