<a href="https://colab.research.google.com/github/jhiasab27/Linear-Algebra---58019/blob/main/LA_Matrix_Algebra_(10_6_21).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Python program to inverse

In [12]:
import numpy as np
A=np.array([[1,2],[4,7]])
#print(A)

invA=np.linalg.inv(A)
print(invA)

[[-7.  2.]
 [ 4. -1.]]


In [13]:
C=np.dot(A,invA)
print(C)

[[1. 0.]
 [0. 1.]]


In [27]:
#Python Program to Transpose a 3x3 Matrix A=[6,1,1],[4,-2,5],[2,8,7]
A=np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(A,"\n")

B=np.transpose(A)
print(B)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]] 

[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


In [32]:
#Python program to inverse a 3x3 matrix A=[6,1,1],[4,-2,5],[2,8,7]
A=np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(A,"\n")

B=np.linalg.inv(A)
print(B,"\n")

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]] 

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]] 



##Program to get the dot product of matrix A & its inverse

In [34]:
AB=np.dot(A,B)
print(AB)

[[ 1.00000000e+00  0.00000000e+00  2.77555756e-17]
 [-1.38777878e-17  1.00000000e+00  1.38777878e-17]
 [-4.16333634e-17  1.38777878e-16  1.00000000e+00]]


###Python Program to inverse and transpose a 4x4 matrix A = ([6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7])

In [41]:
A=np.array([[6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7]])

B=np.linalg.inv(A) #used to inverse a matrix
print("Inverse of Matrix A:\n",B,"\n")

AB=np.dot(A,B) #output should be an identity matrix
print("For checking:\n",AB,"\n")

C=np.transpose(B) #for transposing the values of the matrix
print("Transposed Matrix A:\n",C)

Inverse of Matrix A:
 [[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]] 

For checking:
 [[ 1.00000000e+00  0.00000000e+00  2.77555756e-17  5.55111512e-17]
 [-1.24900090e-16  1.00000000e+00 -5.55111512e-17 -2.77555756e-17]
 [ 2.77555756e-17  0.00000000e+00  1.00000000e+00  1.11022302e-16]
 [-1.52655666e-16 -2.22044605e-16 -8.32667268e-17  1.00000000e+00]] 

Transposed Matrix A:
 [[ 0.13368984 -0.00229183 -0.12987013  0.11000764]
 [ 0.10695187  0.02673797  0.18181818 -0.28342246]
 [ 0.02139037  0.14820474  0.06493506 -0.11382735]
 [-0.09090909 -0.12987013 -0.02597403  0.23376623]]
