<a href="https://colab.research.google.com/github/jhiasab27/Linear-Algebra---58019/blob/main/LA_Coding_Activity_3_(11_3_21).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Coding Activity 3

In [8]:
import numpy as np
A=np.array([[4,10,8],[10,26,26],[8,26,61]]) #matrix A
print(A)

inv_A=np.linalg.inv(A)
print(inv_A)

[[ 4 10  8]
 [10 26 26]
 [ 8 26 61]]
[[ 25.27777778 -11.16666667   1.44444444]
 [-11.16666667   5.          -0.66666667]
 [  1.44444444  -0.66666667   0.11111111]]


In [7]:
B=np.array([[44],[128],[214]]) #matrix B
print(B)

[[ 44]
 [128]
 [214]]


In [6]:
X=np.dot(inv_A,B) #dot product of inv_A and B
print(X)

[[-8.]
 [ 6.]
 [ 2.]]


##Checking

In [5]:
B=np.dot(A,X)
print(B)

[[ 44.]
 [128.]
 [214.]]
