<a href="https://colab.research.google.com/github/jhiasab27/Linear-Algebra---58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Midterm Exam

###Question 1. Create a Python code that displays a square matrix whose length is 5 (10 points)

In [4]:
import numpy as np
A=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]]) #5x5 matrix
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


###Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)

In [10]:
import numpy as np
A=np.eye(3)
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


###Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)

In [33]:
import numpy as np
A=np.array([[1,2,3],[1,2,3],[1,2,3]])
B=np.transpose(A) 

print(A,"matrix A\n")
print(B,"transposed matrix A\n")
print("Resulting symmetrical matrix:\n",np.dot(A,B)) #get the dot product of A and transposed A to get a symmetrical matrix

[[1 2 3]
 [1 2 3]
 [1 2 3]] matrix A

[[1 1 1]
 [2 2 2]
 [3 3 3]] transposed matrix A

Resulting symmetrical matrix:
 [[14 14 14]
 [14 14 14]
 [14 14 14]]


###Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)

In [39]:
import numpy as np
C=np.array([[1,2,3],[2,3,3],[3,4,-2]]) #matrix C
print("Matrix C\n",C, "\n")

inv_C=np.linalg.inv(C) #inverse of matrix C
print("Inverse of matrix C\n",inv_C, "\n")

Matrix C
 [[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]] 

Inverse of matrix C
 [[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]] 



###Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

In [19]:
import numpy as np
A = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(A, "\n")
print("The determinant of the given matrix is: ",round(np.linalg.det(A))) #rounded up determinant

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]] 

The determinant of the given matrix is:  5


###Question 6. Find the roots of the linear equations by showing its python codes (30 points)

5X1 + 4X2 + X3 = 3.4

10X1 + 9X2 + 4X3 = 8.8

10X1 + 13X2 + 15X3 = 19.2

In [35]:
import numpy as np
A=np.array([[5,4,1],[10,9,4],[10,13,15]]) #matrix A
print(A, "matrix A\n")

inv_A=np.linalg.inv(A) #inverse of matrix A
print(inv_A, "inverse of matrix A\n")

B=np.array([[3.4],[8.8],[19.2]]) #matrix B
print(B, "matrix B\n")

X=np.dot(inv_A,B) #the output are the roots
print(X,"roots of the linear equations")
print("Therefore, the roots are: X1=0.2, X2=0.4, X3=0.8\n")

#checking
B=np.dot(A,X)
print("After checking, the results are equal to matrix B:\n",B, "\n")

[[ 5  4  1]
 [10  9  4]
 [10 13 15]] matrix A

[[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]] inverse of matrix A

[[ 3.4]
 [ 8.8]
 [19.2]] matrix B

[[0.2]
 [0.4]
 [0.8]] roots of the linear equations
Therefore, the roots are: X1=0.2, X2=0.4, X3=0.8

After checking, the results are equal to matrix B:
 [[ 3.4]
 [ 8.8]
 [19.2]] 

