<a href="https://colab.research.google.com/github/jhiasab27/Linear-Algebra---58019/blob/main/Practical_Lab_Exam_1_(Linear_Algebra%3B_9_15_21).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Problem 1

In [48]:
import numpy as np
A = np.array([[1,2,3], [4,5,6]]) 
B = np.array([[1,2], [3,4], [5,6]])
C = np.array([[1,2,3], [4,5,6], [7,8,9]]) 
D = np.array([[1,2], [3,4]])

a1=np.dot(A,B)

print("a.\n",a1,"\n")

print("b.\n",D+D, "\n")

print("c.\n",2*C, "\n")

a.
 [[22 28]
 [49 64]] 

b.
 [[2 4]
 [6 8]] 

c.
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]] 



###Problem 2

In [50]:
c = np.array([[5, 3, -1]])

print(c,"\n")
print("Type: ", type(c))
print("Shape: ", c.shape)
print("Dimension:", c.ndim)

[[ 5  3 -1]] 

Type:  <class 'numpy.ndarray'>
Shape:  (1, 3)
Dimension: 2
