<a href="https://colab.research.google.com/github/jhiasab27/Linear-Algebra---58019/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Prelim Exam

###Question 1

In [14]:
import numpy as np
C = np.eye(4) #creates a matrix with a diagonal 1 and fills the rest with zeros

print(C)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


###Question 2

In [16]:
import numpy as np
C = np.eye(4) #from Q1
c=2*C #for doubling the values

print(c)

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


###Question 3

In [19]:
A = ([2,7,4])
B = ([3,9,8])
cross = np.cross(A,B) #cross multiplies vector A and B

print("Matrix A: ",A)
print("Matrix B: ",B)
print("Cross-product: ",cross)

Matrix A:  [2, 7, 4]
Matrix B:  [3, 9, 8]
Cross-product:  [20 -4 -3]
