<a href="https://colab.research.google.com/github/jhiasab27/Linear-Algebra---58019/blob/main/Python_Exercise_1_(9_1_21).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix and Its Operations

In [3]:
#numpy
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array([[6, -3],[2,3]])
print(A+B) #sum = A +B

[[ 1 -3]
 [ 6  4]]


In [4]:
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array([[6, -3],[2,3]])
print(B-A) #difference1 = B - A

[[11 -3]
 [-2  2]]


In [5]:
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array([[6, -3],[2,3]])
print(A-B) #difference2 = A - B

[[-11   3]
 [  2  -2]]
